version: '3'
services:
  top.api:
    container_name: top-api
    restart: always
    build:
      context: .
      target: builder
    networks:
      - nest-test
    ports: 
      - 127.0.0.1:3000:3000
    volumes:
      - ./.env:/app/.env
      - ./:/app
      - /app/node_modules
    command: npm run start:debug
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:4.4.4
    container_name: mongo
    user: root
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - nest-test
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - mongodata:/data/db
    command: --wiredTigerCacheSizeGB 1.5

  dbadmin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - nest-test
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_AUTHDATABASE}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGOEXPRESS_PASSWORD}

networks:
  nest-test:
    driver: bridge

volumes:
  mongodata:

